INSERT INTO regions (region_name)
VALUES ('Kanto'), ('Hoenn'), ('Sinnoh');

INSERT INTO staffranks (rank_name, permission_level)
VALUES ('Owner', 1), ('Admin', 2), ('Moderator', 3), ('User', 5);

INSERT INTO workareas (area_name)
VALUES ('Terrain'),
    ('Buildings'),
    ('Foliage'),
    ('Pokemon'),
    ('StoryNPCs'),
    ('ShopNPCs'),
    ('ChattingNPCs'),
    ('Trainers'),
    ('Items');

INSERT INTO workitemstatuses (status_name)
VALUES ('New'), ('In Progress'), ('Complete');

# Basic Kanto Routes
INSERT INTO routes (region_id, route_name)
VALUES (1, 'Route 1'),
    (1, 'Route 2'),
    (1, 'Route 3'),
    (1, 'Route 4'),
    (1, 'Route 5'),
    (1, 'Route 6'),
    (1, 'Route 7'),
    (1, 'Route 8'),
    (1, 'Route 9'),
    (1, 'Route 10'),
    (1, 'Route 11'),
    (1, 'Route 12'),
    (1, 'Route 13'),
    (1, 'Route 14'),
    (1, 'Route 15'),
    (1, 'Route 16'),
    (1, 'Route 17'),
    (1, 'Route 18'),
    (1, 'Route 19'),
    (1, 'Route 20'),
    (1, 'Route 21'),
    (1, 'Route 22'),
    (1, 'Route 23'),
    (1, 'Route 24'),
    (1, 'Route 25'),
    (1, 'Cerulean Cave'),
    (1, 'Cerulean City'),
    (1, 'Cinnabar Island'),
    (1, 'Celadon City'),
    (1, 'Diglett''s Cave'),
    (1, 'Fuchsia City'),
    (1, 'Indigo Plateau'),
    (1, 'Lavender Town'),
    (1, 'Mt. Moon'),
    (1, 'Pallet Town'),
    (1, 'Pewter City'),
    (1, 'Pokemon Mansion'),
    (1, 'Pokemon Tower'),
    (1, 'Power Plant'),
    (1, 'Rock Tunnel'),
    (1, 'Rocket Hideout'),
    (1, 'Safari Zone'),
    (1, 'Saffron City'),
    (1, 'Seafoam Islands'),
    (1, 'Silph Co.'),
    (1, 'SS Anne'),
    (1, 'Underground Path 5-6'),
    (1, 'Underground Path 7-8'),
    (1, 'Vermilion City'),
    (1, 'Victory Road'),
    (1, 'Viridian City'),
    (1, 'Viridian Forest');

# Kanto - Sevii Islands
INSERT INTO routes (region_id, route_name)
VALUES (1, 'One Island'),
    (1, 'Two Island'),
    (1, 'Three Island'),
    (1, 'Four Island'),
    (1, 'Five Island'),
    (1, 'Six Island'),
    (1, 'Seven Island'),
    (1, 'Kindle Road'),
    (1, 'Treasure Beach'),
    (1, 'Mt. Ember'),
    (1, 'Cape Brink'),
    (1, 'Three Isle Port'),
    (1, 'Three Isle Path'),
    (1, 'Bond Bridge'),
    (1, 'Berry Forest'),
    (1, 'Icefall Cave'),
    (1, 'Five Isle Meadow'),
    (1, 'Memorial Pillar'),
    (1, 'Water Labyrinth'),
    (1, 'Resort Gorgeous'),
    (1, 'Rocket Warehouse'),
    (1, 'Lost Cave'),
    (1, 'Water Path'),
    (1, 'Ruin Valley'),
    (1, 'Dotted Hole'),
    (1, 'Green Path'),
    (1, 'Pattern Bush'),
    (1, 'Outcast Island'),
    (1, 'Altering Cave'),
    (1, 'Trainer Tower'),
    (1, 'Canyon Entrance'),
    (1, 'Sevault Canyon'),
    (1, 'Tanoby Ruins'),
    (1, 'Navel Rock'),
    (1, 'Birth Island');


DELETE FROM routes
WHERE route_name = 'Gnarled Den';

# Hoenn Routes
INSERT INTO routes (region_id, route_name)
VALUES (2, 'Route 101'),
    (2, 'Route 102'),
    (2, 'Route 103'),
    (2, 'Route 104'),
    (2, 'Route 105'),
    (2, 'Route 106'),
    (2, 'Route 107'),
    (2, 'Route 108'),
    (2, 'Route 109'),
    (2, 'Route 110'),
    (2, 'Route 111'),
    (2, 'Route 112'),
    (2, 'Route 113'),
    (2, 'Route 114'),
    (2, 'Route 115'),
    (2, 'Route 116'),
    (2, 'Route 117'),
    (2, 'Route 118'),
    (2, 'Route 119'),
    (2, 'Route 120'),
    (2, 'Route 121'),
    (2, 'Route 122'),
    (2, 'Route 123'),
    (2, 'Route 124'),
    (2, 'Route 125'),
    (2, 'Route 126'),
    (2, 'Route 127'),
    (2, 'Route 128'),
    (2, 'Route 129'),
    (2, 'Route 130'),
    (2, 'Route 131'),
    (2, 'Route 132'),
    (2, 'Route 133'),
    (2, 'Route 134'),
    (2, 'Abandoned Ship'),
    (2, 'Altering Cave'),
    (2, 'Aqua Hideout'),
    (2, 'Artisan Cave'),
    (2, 'Battle Frontier'),
    (2, 'Birth Island'),
    (2, 'Cave of Origin'),
    (2, 'Dewford Town'),
    (2, 'Evergrande City'),
    (2, 'Fallarbor Town'),
    (2, 'Faraway Island'),
    (2, 'Fiery Path'),
    (2, 'Fortree City'),
    (2, 'Granite Cave'),
    (2, 'Jagged Pass'),
    (2, 'Lavaridge Town'),
    (2, 'Lilycove City'),
    (2, 'Littleroot Town'),
    (2, 'Magma Hideout'),
    (2, 'Marine Cave'),
    (2, 'Mauville City'),
    (2, 'Meteor Falls'),
    (2, 'Mirage Cave'),
    (2, 'Mirage Forest'),
    (2, 'Mirage Island'),
    (2, 'Mirage Mountain'),
    (2, 'Mirage Tower'),
    (2, 'Mossdeep City'),
    (2, 'Mt. Chimney'),
    (2, 'Mt. Pyre'),
    (2, 'Navel Rock'),
    (2, 'New Mauville'),
    (2, 'Oldale Town'),
    (2, 'Pacifidlog Town'),
    (2, 'Pathless Plain'),
    (2, 'Petalburg City'),
    (2, 'Petalburg Woods'),
    (2, 'Pokemon League'),
    (2, 'Rustboro City'),
    (2, 'Rusturf Tunnel'),
    (2, 'Safari Zone'),
    (2, 'Scorched Slab'),
    (2, 'Sea Mauville'),
    (2, 'Seafloor Cavern'),
    (2, 'Sealed Chamber'),
    (2, 'Secret Islet'),
    (2, 'Secret Meadow'),
    (2, 'Secret Shore'),
    (2, 'Shoal Cave'),
    (2, 'Sky Pillar'),
    (2, 'Slateport City'),
    (2, 'Sootopolis City'),
    (2, 'Southern Island'),
    (2, 'SS Tidal'),
    (2, 'Terra Cave'),
    (2, 'Trackless Forest'),
    (2, 'Trainer Hill'),
    (2, 'Verdanturf Town'),
    (2, 'Victory Road');