-- Active: 1788819607523@@127.0.0.1@5432@pixelmonweb
CREATE TABLE Regions (
    ID SERIAL PRIMARY KEY,
    REGION_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE Routes (
    ID SERIAL PRIMARY KEY,
    REGION_ID INT REFERENCES Regions(ID),
    ROUTE_NAME VARCHAR(255) NOT NULL
);


CREATE TABLE WorkAreas (
    ID SERIAL PRIMARY KEY,
    AREA_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE StaffRanks (
    ID SERIAL PRIMARY KEY,
    RANK_NAME VARCHAR(255) NOT NULL,
    PERMISSION_LEVEL INT NOT NULL
);

CREATE TABLE Staff (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    RANK_ID INT REFERENCES StaffRanks(ID)
);

CREATE TABLE WorkItemStatuses (
    ID SERIAL PRIMARY KEY,
    STATUS_NAME VARCHAR(255)
);

CREATE TABLE WorkItems (
    ID SERIAL PRIMARY KEY,
    REGION_ID INT REFERENCES Regions(ID),
    ROUTE_ID INT REFERENCES Routes(ID),
    ASSIGNED_TO_ID INT REFERENCES Staff(ID),
    WORK_AREA_ID INT REFERENCES WorkAreas(ID),
    STATUS_ID INT REFERENCES WorkItemStatuses(ID),
    SHORT_DESCRIPTION VARCHAR(255) NOT NULL,
    LONG_DESCRIPTION VARCHAR(1028)
);
